#!/bin/bash

FILE="/etc/motd"
#BOOTTIME=$(who -b | sed -e "s/[^A-Z]*//")
BOOTTIME=$(who -b)
#UPTIME=$(uptime | sed -e "s/ [0-9:]* up />/" -e "s/,.*//")
UPTIME=$(uptime)
#DISK=$(df -h | egrep '(Filesystem)|(/dev/sd)')
DISK=$(df -h)
WHO=$(who)
INSTDATE=$(date +%F)
HOSTNAME=$(hostname)
OSRELASE=$(cat /etc/*release | head -1)
OSDETECT=
#IPADDRES=$(ifconfig eth0 | grep -o '[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*' | head -1)
ETHERADD=$(ifconfig |grep -e ^[a-z] |grep -v lo | awk '{ printf $1 FS}')

if [ -w $FILE ]
  then
    if [[ -n `egrep -o '[0-9]+++-[0-9]++-[0-9]++' $FILE` ]]
    then
      IDATE=$(egrep -o '[0-9]+++-[0-9]++-[0-9]++' $FILE)
      echo "$FILE was in past $IDATE altered" 
      echo "Will be saved as .rpmsave"
      FILE=$FILE.rpmsave
    fi
  else
        logger -p local0.warn -t ME "`id -un` is not allowed to edit $FILE"
        echo "File is not Writeable. You are Not allowed to chance Motd"
    echo "Will be saved as .rpmsave"
    FILE=$FILE.rpmsave
fi

cat << End-of-Message > $FILE
`echo -en "\033[1;31m"`
    * * * * * * * * * * * * * * * * * * * * *:  W A R N I N G  :* * * * * * * * * * * * * * * * * * * * *
    *              THIS SYSTEM IS RESTRICTED TO AUTHORIZED USERS FOR AUTHORIZED USE ONLY                *
    *                  UNAUTHORIZED ACCESS IS STRICTLY PROHIBITED AND MAY BE PUNISHED                   *
    * * * * * * * * * * * * * * * * * * * * *:  W A R N I N G  :* * * * * * * * * * * * * * * * * * * * *
    *                                                                                        $INSTDATE *
End-of-Message
printf "    *           %-16s%-72s*\n" "Boot Time:" "$BOOTTIME" >>$FILE
printf "    *           %-16s%-72s*\n" "Up Time:" "$UPTIME" >>$FILE
printf "    *           %-16s%-72s*\n" "Hostname:" "$HOSTNAME" >>$FILE

for i in $ETHERADD
do
  IP=$(ifconfig $i | grep -o '[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*' | head -1)
  printf "    *           %-16s%-72s*\n" "IP $i:"      "$IP" >>$FILE
done

printf "    *           %-16s%-72s*\n" "OS:"     "$OSRELASE" >>$FILE
printf "    *           %-16s%-72s*\n" "HW:"     "$OSDETECT" >>$FILE
#printf "    *           %-16s%-72s*\n" "IP:"      "$IPADDRES" >>$FILE
printf "    *           %-16s%-72s*\n" "" >>$FILE
printf "    *           %-16s%-72s*\n" "Disk Usage:" "$DISK" >>$FILE
printf "    *           %-16s%-72s*\n" "" >>$FILE
printf "    *           %-16s%-32s*\n" "=================== CURRENTLY ONLINE ===================" >>$FILE
printf "    *           %-16s%-56s*\n" "NAME     LINE         IP ADDRESS" >>$FILE
printf "    *           %-16s%-70s*\n%-16s%-70s*\n" "$WHO" >>$FILE
printf "    *           %-16s%-72s*\n" "" >>$FILE
printf "    *           %-16s%-72s*\n" "" >>$FILE
printf "    *           %-16s%-72s*\n" "Contact:" "KSC Kreate" >>$FILE
printf "    *           %-16s%-72s*\n" "        " "3850 N. 29th Terrace" >>$FILE
printf "    *           %-16s%-72s*\n" "        " "Hollywood, FL 33020" >>$FILE
printf "    *           %-16s%-72s*\n" "" >>$FILE
printf "    *           %-16s%-72s*\n" "Administrator:" "Development Dept." >>$FILE
printf "    *           %-16s%-72s*\n" "" >>$FILE
printf "    *           %-16s%-72s*\n" "Environment:" "Production" >>$FILE

cat << End-of-Message >> $FILE
    *****************************************************************************************************
                      __________              ._____________.__                
                      \______   \ ____ _____  |  \__    ___/|__| _____   ____  
                       |       _// __ \ __  \ |  | |    |   |  |/     \_/ __ \ 
                       |    |   \  ___/ / __ \|  |_|    |   |  |  Y Y  \  ___/ 
                       |____|_  /\___  >____  /____/____|   |__|__|_|  /\___  >
                              \/     \/     \/                       \/     \/ 
`echo -en "\033[0m"`
End-of-Message
